# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MINERVA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_w_and_h', models.DateField()),
                ('teeth', models.IntegerField()),
                ('date_teeth', models.DateField()),
                ('head_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_head', models.DateField()),
                ('uid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
