# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MINERVA', '0004_childdata_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 5, 25, 40, 748586, tzinfo=utc)),
        ),
    ]
