# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MINERVA', '0008_auto_20161019_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 10, 19, 12, 58, 52, 833026)),
        ),
    ]
