# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MINERVA', '0012_auto_20161025_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightandheightdata',
            old_name='uid_child',
            new_name='fullname',
        ),
    ]
