# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MINERVA', '0013_auto_20161107_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightandheightdata',
            old_name='fullname',
            new_name='child',
        ),
    ]
