# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MINERVA', '0015_auto_20161108_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='finemotorchecklist',
            name='uid_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MINERVA.ChildData'),
        ),
        migrations.AddField(
            model_name='grossmotorchecklist',
            name='uid_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MINERVA.ChildData'),
        ),
        migrations.AddField(
            model_name='personalsocialchecklist',
            name='uid_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MINERVA.ChildData'),
        ),
    ]
